### ISSUE TITLE
US 14 : Styling Edit Button & Page

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#24]
## Value Proposition

**As a** ... User
**I want to** ... see a matching design system
**so that** ... I don't get confused.
​

## Description
<img width="361" alt="Bildschirm­foto 2023-03-22 um 23 14 50" src="https://user-images.githubusercontent.com/104009848/227497574-b000857b-abe7-44ed-977f-2c13ad319405.png">

​

## Acceptance Criteria

- [ ] styled edit page & edit button matching rest of the app
      ​

## Tasks

- [ ] create StyledComponents
- [ ] add previous styles
      ​

## Complexity

S

**Comment by Efendi5** [comment]
that looks like a good idea i'm curious how the result looks like

**Comment by SarahWett** [comment]
@Efendi5 hopefully better than at the moment! :)
